### PR TITLE
Stage back end

### PR DESCRIPTION
**Pull request by pstaal**

### CODE REVIEW

**Comment by AygulMalikova** [comment]
Unfortunately, your work is rejected without review because the backend part of the application is not deployed to the server. Please specify the server address in the README.md file.

**Comment by pstaal** [comment]
Add server address to readme

**Comment by AygulMalikova** [comment]
# Summary:
## Backend

### Performance Criteria
- [ ]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [ ] `.eslintrc` required for extending the configuration of `airbnb-base`. It also contains the devDependencies needed for the linter to work correctly;
  **Please add `.eslintrc` file with the required configuration**
  - [x] `.gitignore`. The `.gitignore` file contains at least a `node_modules` folder.
  - [ ] Additionally, an exception for `_id` is added in `.eslintrc`. The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`.
- [ ]  There are no lint errors. When running `npx eslint .` they should be absent.
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [ ]  The following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [x] `POST /signup` creates a user with the data passed inside the request body.
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [ ] `GET /articles` returns all articles saved by the user.
  **This route should return only articles saved by the current user**
  - [x] `POST /articles` creates an article with the data passed inside the request body.
  - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [ ]  API errors are handled:
  **If there is no user with provided email and password you need to send an Authorization error (401) https://httpstatuses.com/401**
  **If you try to register an email that already exists on the server should respond with 409**
  **Now, all errors are returned as HTML instead of JSON with the message field http://joxi.ru/ZrJRMgDikwyj3r**
  - [ ] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [ ] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
  - [ ] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [ ] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [x]  Validation implemented correctly:
  - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
  - [x] Data is validated before being added to the database.
- [ ]  In production mode, the database address is taken from `process.env`.
- [ ]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the private key for creating a JWT is implemented correctly:
  - [x] For the production build, it is stored in an `.env` file, and this file should not be added to Git.
  - [x] In development mode (`process.env.NODE_ENV !== 'production'`), the code runs and works fine, and an error won't occur if there is no `.env` file present.

### Best Practices
- [ ]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [ ]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [ ]  Centralized error handling is described inside a separate module.
- [ ]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [ ] Correct:  domain-name.tk/api or api.domain-name.tk
  - [ ] Incorrect: domain-name.tk


### Recommendations
- [ ]  For API errors, classes have been created to extend the Error constructor.
- [ ]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
  - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [ ] Application constants (response and error messages) are stored inside a separate file with constants.
- [ ]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [ ]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 39

## Additional comments:
Good job! 
You have a well-structured and clean code, all the necessary functionality is implemented. 

But there are small issues that you need to fix (see the Performance Criteria section).

There are also a few things I'd like you to check in the Best Practices and Recommendations sections. These are not mistakes, but your project could be improved by following these items in the checklist.

I remind you that your work will be accepted as soon as you receive at least 80 points. Good luck!

**Comment by pstaal** [comment]
new version

**Comment by AygulMalikova** [comment]
# Summary:
## Backend

### Performance Criteria
- [ ]  The repository contains all the necessary infrastructure files:
    - [x] `package.json`;
    - [x] `.editorconfig`;
    - [ ] `.eslintrc` required for extending the configuration of `airbnb-base`. It also contains the devDependencies needed for the linter to work correctly;
      **Please add `.eslintrc` file with required configuration**
    - [x] `.gitignore`. The `.gitignore` file contains at least a `node_modules` folder.
    - [ ] Additionally, an exception for `_id` is added in `.eslintrc`. The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`.
- [ ]  There are no lint errors. When running `npx eslint .` they should be absent.
- [x]  The scripts section of the package.json file contains the following:
    - [x] An `npm run start` command that starts the server on `localhost:3000`.
    - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  The following routes function as described:
    - [x] A request to `GET /users/me` returns information about the user (email and name).
    - [x] `POST /signup` creates a user with the data passed inside the request body.
    - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
    - [x] `GET /articles` returns all articles saved by the user.
    - [x] `POST /articles` creates an article with the data passed inside the request body.
    - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [ ]  API errors are handled:
  **If there is no user with provided email and password you need to send an Authorization error (401) https://httpstatuses.com/401**
  **If you try to register an email that already exists on the server should respond with 409**
  **Now, all errors are returned as HTML instead of JSON with the message field http://joxi.ru/v29zpKZHjzwldA**
    - [ ] Error status codes are used: 400, 401, 403, 404, 409, 500.
    - [ ] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
    - [ ] The error message matches its type.
    - [x] Asynchronous handlers end with a `catch()` block.
    - [ ] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
    - [x] Passwords are stored in a hashed form.
    - [x] The API does not return a password hash to the client.
- [x]  Validation implemented correctly:
    - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
    - [x] Data is validated before being added to the database.
- [ ]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the private key for creating a JWT is implemented correctly:
    - [x] For the production build, it is stored in an `.env` file, and this file should not be added to Git.
    - [x] In development mode (`process.env.NODE_ENV !== 'production'`), the code runs and works fine, and an error won't occur if there is no `.env` file present.


### Best Practices
- [x]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [ ]  Validation is described in a separate module.
- [x]  Logging is set up:
    - [x] All requests and responses are logged to the `request.log` file.
    - [x] All errors are logged to the `error.log` file.
    - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
    - [x] Correct:  domain-name.tk/api or api.domain-name.tk
    - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
    - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
    - [x] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 75

## Additional comments:
Very well! You've fixed a lot of bugs and you're heading in the right direction!
There are very few mistakes left to get 80 points and your work will be accepted. 

Please add eslintrc configuration to your project. Also, please make sure your remote server is up to date because some requests respond as before.

Good luck!

**Comment by AygulMalikova** [comment]
Unfortunately, your work is rejected without review because when running your project locally there is an error ( MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined"). Please note that I do not have .env file locally and that's why the DATABASE_URL is set to undefined. You need to add a default value: `const { PORT = 3000, DATABASE_URL = 'mongodb://localhost:27017/newsdb'} = process.env;`. Moreover, your remote server doesn't respond. Please make sure that it is accessible. Good luck!

**Comment by pstaal** [comment]
Hi @AygulMalikova I have made the change to the code. The reason the remote server is not responding I have no idea? The tutors have not yet been able find a solution either. Maybe you can helpt? I have restarted everything (pm2, nginx, mongo) it all seems to working. The problem began when Google Cloud shut down my vm because I needed to update billing. After I did this, it all seem to be working again except for a server not responding. Pushing code to the server, running local processes all works.

**Comment by AygulMalikova** [comment]
# Summary:
## Backend

### Performance Criteria
- [ ]  The repository contains all the necessary infrastructure files:
    - [x] `package.json`;
    - [x] `.editorconfig`;
    - [ ] `.eslintrc` required for extending the configuration of `airbnb-base`. It also contains the devDependencies needed for the linter to work correctly;
      **eslint package is not installed**
    - [x] `.gitignore`. The `.gitignore` file contains at least a `node_modules` folder.
    - [ ] Additionally, an exception for `_id` is added in `.eslintrc`. The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`.
- [ ]  There are no lint errors. When running `npx eslint .` they should be absent.
- [x]  The scripts section of the package.json file contains the following:
    - [x] An `npm run start` command that starts the server on `localhost:3000`.
    - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  The following routes function as described:
    - [x] A request to `GET /users/me` returns information about the user (email and name).
    - [x] `POST /signup` creates a user with the data passed inside the request body.
    - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
    - [x] `GET /articles` returns all articles saved by the user.
    - [x] `POST /articles` creates an article with the data passed inside the request body.
    - [x] `DELETE /articles/:articleId` deletes the saved article using `_id`.
- [x]  Users can't delete saved articles from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and article routes are described in separate files.
- [ ]  API errors are handled:
  **If there is no user with provided email and password you need to send an Authorization error (401) https://httpstatuses.com/401**
  **If you try to register an email that already exists on the server should respond with 409.**
  **I recommend using the `err.code === 11000` check to determine the email address conflict without checking for the name of the error, since the name of the error may differ depending on the version of mongoose or MongoDb (it can be named as `"MongoError"` or `"MongoServerError"`);**
    - [ ] Error status codes are used: 400, 401, 403, 404, 409, 500.
    - [ ] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
    - [ ] The error message matches its type.
    - [x] Asynchronous handlers end with a `catch()` block.
    - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
    - [x] Passwords are stored in a hashed form.
    - [x] The API does not return a password hash to the client.
- [x]  Validation implemented correctly:
    - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
    - [x] Data is validated before being added to the database.
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the private key for creating a JWT is implemented correctly:
    - [x] For the production build, it is stored in an `.env` file, and this file should not be added to Git.
    - [x] In development mode (`process.env.NODE_ENV !== 'production'`), the code runs and works fine, and an error won't occur if there is no `.env` file present.

### Best Practices
- [x]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [ ]  Validation is described in a separate module.
- [x]  Logging is set up:
    - [x] All requests and responses are logged to the `request.log` file.
    - [x] All errors are logged to the `error.log` file.
    - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
    - [x] Correct:  domain-name.tk/api or api.domain-name.tk
    - [x] Incorrect: domain-name.tk

### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [x]  Configuration and constants are stored in separate files:
    - [x] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
    - [x] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 83

## Additional comments:
Your work is almost accepted, well done! You have scored enough points, but unfortunately, I cannot accept the project without a working remote server. Please contact your tutor for help. In your project, there is still an opportunity to improve it, and it would be great if you fix them (see the checklist). Good luck!

**Comment by AygulMalikova** [comment]
You did a great job, thank you for that! But unfortunately, your remote server is still not available. I will accept your work, but please keep in mind that in the next stage you will need it. I don't want to take up your time so that you can start the next stage already. I hope that you will be able to figure it out and your remote api will work properly. I was glad to check your work. I wish you success!

**Pull request merged**
